kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: spire-broker-alwaysallow
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            authorization-mode: AlwaysAllow
